services:
  rabbitmq:
    image: rabbitmq:3.13.7-alpine
    hostname: ${RABBITMQ_HOST}
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  mongo:
      image: mongo:8.0.1-noble
      container_name: mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

volumes:
  rabbitmq-data:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MONGODB_VOLUME_PATH}