# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import encoder_pb2 as encoder__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in encoder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/encoderservice.EncoderService/Encode',
                request_serializer=encoder__pb2.EncodeRequest.SerializeToString,
                response_deserializer=encoder__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.CountTokens = channel.unary_unary(
                '/encoderservice.EncoderService/CountTokens',
                request_serializer=encoder__pb2.CountTokensRequest.SerializeToString,
                response_deserializer=encoder__pb2.CountTokensResponse.FromString,
                _registered_method=True)
        self.SplitText = channel.unary_unary(
                '/encoderservice.EncoderService/SplitText',
                request_serializer=encoder__pb2.SplitTextRequest.SerializeToString,
                response_deserializer=encoder__pb2.SplitTextResponse.FromString,
                _registered_method=True)


class EncoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=encoder__pb2.EncodeRequest.FromString,
                    response_serializer=encoder__pb2.EncodeResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=encoder__pb2.CountTokensRequest.FromString,
                    response_serializer=encoder__pb2.CountTokensResponse.SerializeToString,
            ),
            'SplitText': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitText,
                    request_deserializer=encoder__pb2.SplitTextRequest.FromString,
                    response_serializer=encoder__pb2.SplitTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encoderservice.EncoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('encoderservice.EncoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encoderservice.EncoderService/Encode',
            encoder__pb2.EncodeRequest.SerializeToString,
            encoder__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encoderservice.EncoderService/CountTokens',
            encoder__pb2.CountTokensRequest.SerializeToString,
            encoder__pb2.CountTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encoderservice.EncoderService/SplitText',
            encoder__pb2.SplitTextRequest.SerializeToString,
            encoder__pb2.SplitTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
