from core.logger import get_logger
from grpc_generated.encoder_pb2_grpc import EncoderServiceServicer
from langchain_text_splitters import RecursiveCharacterTextSplitter
from model_manager import ModelManager


